export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        'surface': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#4a4455',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'outline': '#7b7487',
        'outline-variant': '#ccc3d8',
        'surface-tint': '#732ee4',
        'primary': '#630ed4',
        'on-primary': '#ffffff',
        'primary-container': '#7c3aed',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#d2bbff',
        'secondary': '#4b41e1',
        'on-secondary': '#ffffff',
        'secondary-container': '#645efb',
        'on-secondary-container': '#fffbff',
        'tertiary': '#005b3d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007650',
        'on-tertiary-container': '#76ffc2',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-secondary-fixed': '#0f0069',
        'on-secondary-fixed-variant': '#3323cc',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'background': '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-3xl': '3rem',
        'space-2xs': '0.125rem',
        'gutter-lg': '1.5rem',
        'space-2xl': '2rem',
        'margin': '1.5rem',
        'space-md': '0.75rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
        'space-sm': '0.5rem',
        'gutter': '1rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
      },
      fontFamily: {
        'body-lg': ['Manrope'],
        'headline-lg': ['Plus Jakarta Sans'],
        'numeric-currency': ['Plus Jakarta Sans'],
        'body-md': ['Manrope'],
        'label-lg': ['Plus Jakarta Sans'],
        'body-sm': ['Manrope'],
        'label-md': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'title-sm': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'numeric-currency': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-sm': ['15px', { lineHeight: '22px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
